-- ============================================================================
-- Migration: User-Specific Claim Requirements
-- Timestamp: 20260929150000
-- Description:
--   Transforms claim_requirements from global templates into individual,
--   user-specific requirements linked to public.profiles(id).
--   Enforces uniqueness on (profile_id, claim_type) so each user has at most
--   one independent CASH requirement and one independent VEHICLE requirement.
--   Updates RLS policies so normal users can only query their own requirements,
--   while administrators maintain full management capabilities.
-- ============================================================================

-- 1. Add profile_id column referencing public.profiles(id)
ALTER TABLE public.claim_requirements
  ADD COLUMN IF NOT EXISTS profile_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE;

-- 2. Drop the legacy global UNIQUE constraint on claim_type
-- In PostgreSQL the constraint generated by "claim_type TEXT UNIQUE" is claim_requirements_claim_type_key
ALTER TABLE public.claim_requirements
  DROP CONSTRAINT IF EXISTS claim_requirements_claim_type_key;

-- 3. Create index and composite unique constraint for user-specific claim requirements
-- Each user (profile_id) can have at most one CASH and one VEHICLE requirement
CREATE UNIQUE INDEX IF NOT EXISTS uq_claim_requirements_profile_claim_type
  ON public.claim_requirements(profile_id, claim_type)
  WHERE profile_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_claim_requirements_profile_id
  ON public.claim_requirements(profile_id);

CREATE INDEX IF NOT EXISTS idx_claim_requirements_profile_status
  ON public.claim_requirements(profile_id, status);

-- 4. Enable Row Level Security (RLS)
ALTER TABLE public.claim_requirements ENABLE ROW LEVEL SECURITY;

-- 5. Drop outdated global RLS policies
DROP POLICY IF EXISTS "claim_requirements_select_policy" ON public.claim_requirements;
DROP POLICY IF EXISTS "claim_requirements_admin_mutation" ON public.claim_requirements;

-- 6. New user-specific RLS policies:
-- Authenticated users may ONLY view their own claim requirements (profile_id = auth.uid())
-- Administrators may view all claim requirements
CREATE POLICY "claim_requirements_select_policy" ON public.claim_requirements
  FOR SELECT
  TO authenticated
  USING (
    profile_id = auth.uid()
    OR public.is_admin()
  );

-- Administrative mutation policy:
-- Only verified administrators may create, modify, or delete user claim requirements
CREATE POLICY "claim_requirements_admin_mutation" ON public.claim_requirements
  FOR ALL
  TO authenticated
  USING (public.is_admin())
  WITH CHECK (public.is_admin());
